import {
  acceptWorkspaceInvite,
  createApiKey,
  createWebhookDestination,
  createSupportRequest,
  createWorkspaceInvite,
  declineWorkspaceInvite,
  deleteWebhookDestination,
  getAccountSummary,
  getDashboardOverview,
  getNotificationSettings,
  getOnboardingState,
  listPendingInvites,
  listApiKeys,
  listAuditLogs,
  listNotificationDeliveries,
  listSupportRequests,
  listUserWorkspaces,
  listWorkspaceMembers,
  removeWorkspaceMember,
  revokeApiKey,
  revokeWorkspaceInvite,
  listWebhookDestinations,
  switchActiveWorkspace,
  updateWorkspaceMemberRole,
  updateNotificationSettings,
  updateWorkspaceLocale,
  updateOnboardingStep,
  updateWebhookDestination,
} from "./account"
import { listScanIssues } from "./issues"
import { getReportById, listReports } from "./reports"
import { getLatestScan, getScan, listWebsiteScans } from "./scans"
import {
  createWebsite,
  getWebsite,
  listWebsites,
  updateNextCheck,
  updateWebsiteDeviceType,
} from "./website"

export const router = {
  getAccountSummary: getAccountSummary,
  listUserWorkspaces: listUserWorkspaces,
  switchActiveWorkspace: switchActiveWorkspace,
  listPendingInvites: listPendingInvites,
  acceptWorkspaceInvite: acceptWorkspaceInvite,
  declineWorkspaceInvite: declineWorkspaceInvite,
  getDashboardOverview: getDashboardOverview,
  getNotificationSettings: getNotificationSettings,
  updateNotificationSettings: updateNotificationSettings,
  updateWorkspaceLocale: updateWorkspaceLocale,
  listWebhookDestinations: listWebhookDestinations,
  createWebhookDestination: createWebhookDestination,
  updateWebhookDestination: updateWebhookDestination,
  deleteWebhookDestination: deleteWebhookDestination,
  listWorkspaceMembers: listWorkspaceMembers,
  createWorkspaceInvite: createWorkspaceInvite,
  revokeWorkspaceInvite: revokeWorkspaceInvite,
  updateWorkspaceMemberRole: updateWorkspaceMemberRole,
  removeWorkspaceMember: removeWorkspaceMember,
  listAuditLogs: listAuditLogs,
  listNotificationDeliveries: listNotificationDeliveries,
  getOnboardingState: getOnboardingState,
  updateOnboardingStep: updateOnboardingStep,
  listApiKeys: listApiKeys,
  createApiKey: createApiKey,
  revokeApiKey: revokeApiKey,
  listSupportRequests: listSupportRequests,
  createSupportRequest: createSupportRequest,
  listWebsites: listWebsites,
  createWebsite: createWebsite,
  getWebsite: getWebsite,
  listWebsiteScans: listWebsiteScans,
  updateWebsiteNextCheck: updateNextCheck,
  updateWebsiteDeviceType: updateWebsiteDeviceType,
  getLatestScan: getLatestScan,
  listScanIssues: listScanIssues,
  getScan: getScan,

  listReports: listReports,
  getReportById: getReportById,
}
