import {
  createApiKey,
  createWebhookDestination,
  createSupportRequest,
  deleteWebhookDestination,
  getAccountSummary,
  getDashboardOverview,
  getNotificationSettings,
  getOnboardingState,
  listApiKeys,
  listAuditLogs,
  listNotificationDeliveries,
  listSupportRequests,
  revokeApiKey,
  listWebhookDestinations,
  updateNotificationSettings,
  updateWorkspaceLocale,
  updateOnboardingStep,
  updateWebhookDestination,
} from "./account"
import { listScanIssues } from "./issues"
import { getReportById, listReports } from "./reports"
import { getLatestScan, getScan, listWebsiteScans } from "./scans"
import {
  createWebsite,
  deleteWebsite,
  getWebsite,
  listWebsites,
  updateWebsite,
  updateNextCheck,
  updateWebsiteDeviceType,
} from "./website"

export const router = {
  getAccountSummary: getAccountSummary,
  getDashboardOverview: getDashboardOverview,
  getNotificationSettings: getNotificationSettings,
  updateNotificationSettings: updateNotificationSettings,
  updateWorkspaceLocale: updateWorkspaceLocale,
  listWebhookDestinations: listWebhookDestinations,
  createWebhookDestination: createWebhookDestination,
  updateWebhookDestination: updateWebhookDestination,
  deleteWebhookDestination: deleteWebhookDestination,
  listAuditLogs: listAuditLogs,
  listNotificationDeliveries: listNotificationDeliveries,
  getOnboardingState: getOnboardingState,
  updateOnboardingStep: updateOnboardingStep,
  listApiKeys: listApiKeys,
  createApiKey: createApiKey,
  revokeApiKey: revokeApiKey,
  listSupportRequests: listSupportRequests,
  createSupportRequest: createSupportRequest,
  listWebsites: listWebsites,
  createWebsite: createWebsite,
  getWebsite: getWebsite,
  updateWebsite: updateWebsite,
  deleteWebsite: deleteWebsite,
  listWebsiteScans: listWebsiteScans,
  updateWebsiteNextCheck: updateNextCheck,
  updateWebsiteDeviceType: updateWebsiteDeviceType,
  getLatestScan: getLatestScan,
  listScanIssues: listScanIssues,
  getScan: getScan,

  listReports: listReports,
  getReportById: getReportById,
}
